package com.learning.core_java_spring_lab;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class CoreJavaSpringLabApplication {

	public static void main(String[] args) {
		SpringApplication.run(CoreJavaSpringLabApplication.class, args);
	}

}
